import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'dart:math';

class PortfolioCertService {
  final _firestore = FirebaseFirestore.instance;
  final _auth = FirebaseAuth.instance;

  // ── 1. إدارة البورتفوليو (Subcollection داخل المستخدم) ──
  
  /// جلب عناصر البورتفوليو (شهادات خارجية، مشاريع، كورسات)
  Stream<List<Map<String, dynamic>>> getPortfolioStream(String userId) {
    return _firestore
        .collection('users')
        .doc(userId)
        .collection('portfolio')
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs.map((doc) {
              final data = doc.data();
              data['id'] = doc.id; // إضافة المعرف ليسهل التعامل معه
              return data;
            }).toList());
  }

  /// إضافة عنصر جديد للبورتفوليو
  Future<void> addPortfolioItem(String userId, Map<String, dynamic> data) async {
    data['createdAt'] = FieldValue.serverTimestamp();
    await _firestore.collection('users').doc(userId).collection('portfolio').add(data);
  }

  /// تحديث عنصر موجود
  Future<void> updatePortfolioItem(String userId, String itemId, Map<String, dynamic> data) async {
    await _firestore.collection('users').doc(userId).collection('portfolio').doc(itemId).update(data);
  }

  /// حذف عنصر
  Future<void> deletePortfolioItem(String userId, String itemId) async {
    await _firestore.collection('users').doc(userId).collection('portfolio').doc(itemId).delete();
  }

  // ── 2. إدارة الشهادات الداخلية (Root Collection) ──

  /// جلب شهادات المنصة الداخلية لطالب معين
  Stream<List<Map<String, dynamic>>> getInternalCertsStream(String userId) {
    return _firestore
        .collection('certificates')
        .where('userId', isEqualTo: userId)
        .orderBy('issuedAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs.map((doc) {
              final data = doc.data();
              data['id'] = doc.id;
              return data;
            }).toList());
  }

  /// توليد كود تحقق فريد (مثال: FRM-2026-X9K2M5)
  static String generateVerificationCode() {
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // استبعدنا O, 0, 1 لتجنب اللبس
    final random = Random();
    final randomPart = List.generate(6, (_) => chars[random.nextInt(chars.length)]).join();
    return 'FRM-${DateTime.now().year}-$randomPart';
  }

  /// إضافة شهادة داخلية جديدة (تُولد تلقائياً أو يدوياً)
  Future<void> addInternalCertificate(Map<String, dynamic> data) async {
    data['verificationCode'] = generateVerificationCode();
    data['issuedAt'] = FieldValue.serverTimestamp();
    data['autoGenerated'] = data['autoGenerated'] ?? true;
    await _firestore.collection('certificates').add(data);
  }

  /// دالة التحقق من صحة كود الشهادة (يستخدمها المسؤول)
  Future<Map<String, dynamic>?> verifyCode(String code) async {
    final snapshot = await _firestore
        .collection('certificates')
        .where('verificationCode', isEqualTo: code.toUpperCase().trim())
        .limit(1)
        .get();
    
    return snapshot.docs.isNotEmpty ? snapshot.docs.first.data() : null;
  }
}