// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMe2jwkPHneohNQOg_D_GfIGz34c4Wq80',
    appId: '1:657050782727:web:12162875d73f9c3544eea2',
    messagingSenderId: '657050782727',
    projectId: 'formanova-a3d7c',
    authDomain: 'formanova-a3d7c.firebaseapp.com',
    storageBucket: 'formanova-a3d7c.firebasestorage.app',
    measurementId: 'G-3PK00M7MXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjuiUb7DGy4IvqiYKsZDK99vHe30epdNs',
    appId: '1:657050782727:android:2e2005e7d0508e4444eea2',
    messagingSenderId: '657050782727',
    projectId: 'formanova-a3d7c',
    storageBucket: 'formanova-a3d7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdmCeo-nGnEKFSDX-NUhMExItHt3kTrY',
    appId: '1:657050782727:ios:2786ca49ae47aec944eea2',
    messagingSenderId: '657050782727',
    projectId: 'formanova-a3d7c',
    storageBucket: 'formanova-a3d7c.firebasestorage.app',
    iosBundleId: 'com.example.minipr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdmCeo-nGnEKFSDX-NUhMExItHt3kTrY',
    appId: '1:657050782727:ios:2786ca49ae47aec944eea2',
    messagingSenderId: '657050782727',
    projectId: 'formanova-a3d7c',
    storageBucket: 'formanova-a3d7c.firebasestorage.app',
    iosBundleId: 'com.example.minipr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMe2jwkPHneohNQOg_D_GfIGz34c4Wq80',
    appId: '1:657050782727:web:c66bde35c5e6340544eea2',
    messagingSenderId: '657050782727',
    projectId: 'formanova-a3d7c',
    authDomain: 'formanova-a3d7c.firebaseapp.com',
    storageBucket: 'formanova-a3d7c.firebasestorage.app',
    measurementId: 'G-WB56V30WCE',
  );
}
